### ISSUE TITLE
AttributeError: 'NoneType' adding cityjson files on Mac

### ISSUE THREAD

**Issue by Serranowski** [cityjson/cityjson-qgis-plugin#60]
When trying to add a new cityjson file on Mac using the plugin, I always get the following error:

```
2024-09-15T13:05:12     WARNING    Traceback (most recent call last):
              File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/cityjson_loader.py", line 113, in select_cityjson_file
              self.update_file_information(filename)
              File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/cityjson_loader.py", line 171, in update_file_information
              raise exp
              File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/cityjson_loader.py", line 156, in update_file_information
              self.dlg.crsLineEdit.setText(get_model_epsg(model))
              File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/core/loading.py", line 159, in get_model_epsg
              return m.group(3)
             AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by GinaStavropoulou** [comment]
Could you please share a cityjson file that causes this error. That way I can replicate.

**Comment by StefanCiesilski** [comment]
@GinaStavropoulou Same Problme on Windows with QGIS 3.42
The testfile is here:

[DETHL51P0000A27u_mit_CS_export__v3.zip](https://github.com/user-attachments/files/21317018/DETHL51P0000A27u_mit_CS_export__v3.zip)

Thanks

Ein Fehler trat bei der Ausführung von Python-Code auf: 

AttributeError: 'NoneType' object has no attribute 'group' 
Traceback (most recent call last):
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CityJSON-loader\cityjson_loader.py", line 113, in select_cityjson_file
    self.update_file_information(filename)
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CityJSON-loader\cityjson_loader.py", line 171, in update_file_information
    raise exp
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CityJSON-loader\cityjson_loader.py", line 156, in update_file_information
    self.dlg.crsLineEdit.setText(get_model_epsg(model))
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CityJSON-loader\core\loading.py", line 159, in get_model_epsg
    return m.group(3)
           ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'


Python-Version: 3.12.9 (main, Feb  7 2025, 14:34:44) [MSC v.1938 64 bit (AMD64)] 
QGIS-Version: 3.42.0-Münster Münster, feb8023300 

Python-Pfad:
C:/osgeo4w/apps/qgis/./python
C:/Users/ciesilski/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/ciesilski/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/osgeo4w/apps/qgis/./python/plugins
C:\osgeo4w\apps\grass\grass84\etc\python
C:\WINDOWS\system32
C:\osgeo4w\bin\python312.zip
C:\osgeo4w\apps\Python312\DLLs
C:\osgeo4w\apps\Python312\Lib
C:\osgeo4w\bin
C:\osgeo4w\apps\Python312
C:\osgeo4w\apps\Python312\Lib\site-packages
C:\osgeo4w\apps\Python312\Lib\site-packages\win32
C:\osgeo4w\apps\Python312\Lib\site-packages\win32\lib
C:\osgeo4w\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/ciesilski/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/ciesilski/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask
C:/Users/ciesilski/AppData/Roaming/QGIS/QGIS3/profiles/default/project_templates

**Comment by GinaStavropoulou** [comment]
Unfortunately, I cannot reproduce this error with the file you sent me - the file is being loaded successfully. Which version of the plugin are you using?

**Comment by StefanCiesilski** [comment]
Hello @GinaStavropoulou , I had 0.8.1. It works with 0.8.2.
Great, thank you very much.
